# Generated by Django 5.0.14 on 2025-12-24 09:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("brands", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LicenseKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64, unique=True)),
                ("customer_email", models.EmailField(db_index=True, max_length=254)),
                ("external_reference", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="license_keys",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "license_keys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("valid", "Valid"),
                            ("suspended", "Suspended"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        default="valid",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("max_seats", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="brands.product",
                    ),
                ),
                (
                    "license_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="licenses",
                        to="licenses.licensekey",
                    ),
                ),
            ],
            options={
                "db_table": "licenses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("license_key_created", "License Key Created"),
                            ("license_created", "License Created"),
                            ("license_renewed", "License Renewed"),
                            ("license_suspended", "License Suspended"),
                            ("license_resumed", "License Resumed"),
                            ("license_cancelled", "License Cancelled"),
                            ("activation_created", "Activation Created"),
                            ("activation_deactivated", "Activation Deactivated"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("brand", "Brand System"),
                            ("product", "End-User Product"),
                            ("customer", "Customer"),
                            ("system", "System"),
                            ("admin", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_id", models.CharField(max_length=255)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="licenses.license",
                    ),
                ),
                (
                    "license_key",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="licenses.licensekey",
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("instance_id", models.CharField(max_length=500)),
                ("instance_name", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activations",
                        to="licenses.license",
                    ),
                ),
            ],
            options={
                "db_table": "activations",
                "ordering": ["-activated_at"],
                "indexes": [
                    models.Index(
                        fields=["license", "instance_id"], name="activations_license_5a436b_idx"
                    ),
                    models.Index(fields=["is_active"], name="activations_is_acti_ae5a13_idx"),
                    models.Index(fields=["instance_id"], name="activations_instanc_93a23c_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="activation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("license", "instance_id"),
                name="unique_active_activation",
            ),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(fields=["customer_email"], name="license_key_custome_dc5384_idx"),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["brand", "customer_email"], name="license_key_brand_i_466ce2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="licensekey",
            index=models.Index(
                fields=["external_reference"], name="license_key_externa_eba4c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["license_key", "product"], name="licenses_license_1d5c38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["status"], name="licenses_status_c60f55_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["expires_at"], name="licenses_expires_d6ad63_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["license"], name="audit_logs_license_be534a_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["license_key"], name="audit_logs_license_9bb925_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["action"], name="audit_logs_action_31f574_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["created_at"], name="audit_logs_created_262184_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["actor_type", "actor_id"], name="audit_logs_actor_t_3f370f_idx"
            ),
        ),
    ]
