# Generated by Django 5.0.14 on 2025-12-24 09:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("api_key_hash", models.CharField(max_length=255)),
                ("webhook_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "brands",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["slug"], name="brands_slug_6a4b1c_idx"),
                    models.Index(fields=["is_active"], name="brands_is_acti_101dba_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("default_max_seats", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="brands.brand",
                    ),
                ),
            ],
            options={
                "db_table": "products",
                "ordering": ["brand", "name"],
                "indexes": [
                    models.Index(fields=["brand", "slug"], name="products_brand_i_109c41_idx"),
                    models.Index(fields=["is_active"], name="products_is_acti_cb485f_idx"),
                ],
                "unique_together": {("brand", "slug")},
            },
        ),
    ]
